version: "3.8"
services:
  db:
    #image: mcr.microsoft.com/azure-sql-edge # PARA MAC
    #image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04 # USAR essa versão no linux
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_USER: ${SQL_SERVER_USER_NAME}
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_SERVER_PASS}
      MSSQL_DATABASE: appointmentNotes
    volumes:
      - ${PWD}/.data/appointmentNotes:/var/opt/mssql