
google:
  auth:
    redirectUri: https://3283-191-221-193-141.sa.ngrok.io
    clientSecret: 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
    clientId: 119876353782-5lu09i7mfu1omm23r6s9so1i9m5hiejg.apps.googleusercontent.com
    googleAuthApplicationUrl: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id={clientId}&redirect_uri={redirectUri}&scope=openid%20email%20profile&prompt=select_account
    googleTokenUrlRequest: code={loginAuthenticateCode}&client_id={clientId}&client_secret={clientSecret}&redirect_uri={redirectUri}&grant_type=authorization_code