
google:
  auth2:
    redirectUri: https://6dee-191-221-193-141.sa.ngrok.io
    clientSecret: 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
    clientId: 119876353782-5lu09i7mfu1omm23r6s9so1i9m5hiejg.apps.googleusercontent.com
    googleAuthApplicationUrl: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id={clientId}&redirect_uri={redirectUri}&scope=openid%20email%20profile&prompt=select_account
    googleTokenUrlRequest: code={loginAuthenticateCode}&client_id={clientId}&client_secret={clientSecret}&redirect_uri={redirectUri}&grant_type=
    tokenInfoUrl: https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=
    userInfoUrl: https://www.googleapis.com/oauth2/v1/userinfo?access_token=
    exchangeCodeForToken:
      headerName: Content-Type
      headerValue: application/x-www-form-urlencoded
      requestUrl: https://oauth2.googleapis.com/token
      jsonParameter: access_token

quarkus:
  datasource:
    db-kind: mssql
    username: ${SQL_SERVER_USER}
    password: ${SQL_SERVER_PASS}
    jdbc:
      url: ${SQL_SERVER_DB_URL}
  hibernate-orm:
    database:
      generation: update
  package:
    type: uber-jar
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    schemas: ${SCHEMA_DB_NAME}
    clean-at-start: false
